name: Build& Deploy Spring APP
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy social
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
      users: actions/checkout@v3
        - name: checkout code
          users: actions/checkout@v3
          with:
            distribution: 'corretto'
            java-version: 11
        - name: unit-test
          run: mvn -B test --file pom.xml
        - name: Build the Application
          run:
            mvn clean
            mvn -B package --file pom.xml

